### ISSUE TITLE
Return an AbstractFill from view?

### ISSUE THREAD

**Issue by tkf** [JuliaArrays/FillArrays.jl#84]
As it is planned to return an `AbstractRange` from `view(::AbstractRange, ...)` https://github.com/JuliaLang/julia/pull/26872, I think similarly it makes sense to return an `AbstractFill` from `view(::AbstractFill, ...)`.  I think it is also compatible with `reshape(::AbstractFill, ...) :: AbstractFill`. What do you think?

**Comment by dlfivefifty** [comment]
Ha I came across this issue and was planning to propose this change. I think this is a great idea.

**Comment by dlfivefifty** [comment]
I worked around this in LazyArrays.jl: https://github.com/JuliaArrays/LazyArrays.jl/blob/42823c66a0344f61fafab1da96db5260079afd36/src/lazybroadcasting.jl#L213

But still preferable to overload `view` as you suggest.

**Comment by dlfivefifty** [comment]
Ha, just deleted a long post why this is a bad idea because range doesn't do it when I noticed `range` does!
```julia
julia> view(1:5, 1:3)
1:3
```

That said, #125 makes me hesitant that downstream packages will assume that `view` returns a `SubArray`, or at the very least something that satisfies the implicit subarray interface, e.g.
```julia
v == parent(v)[parentindices(v)...]
```
In fact the docs for `view` hint strongly that this is required:
> Like getindex, but returns a view into the parent array A with the given
>  indices instead of making a copy
Since this is inconsistent with the behaviour of ranges I'm going to make a PR to alter the docs for `view`.

**Comment by dlfivefifty** [comment]
This has been implemented.
